services:

  mongodb:
    image: mongo:latest
    container_name: forever-mongo
    ports:
      - "27017:27017"

  backend:
    image: 623271128010.dkr.ecr.us-east-1.amazonaws.com/forever-backend:latest
    container_name: forever-backend
    ports:
      - "4000:4000"
    depends_on:
      - mongodb

  frontend:
    image: 623271128010.dkr.ecr.us-east-1.amazonaws.com/forever-frontend:latest
    container_name: forever-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

  admin:
    image: 623271128010.dkr.ecr.us-east-1.amazonaws.com/forever-admin:latest
    container_name: forever-admin
    ports:
      - "3001:80"
    depends_on:
      - backend